export const diccPlaystation = {
    //🔵 EXCLUSIVOS DE PS5
    "a quiet place": "https://i.ibb.co/kgLvJ100/1.jpg",
    "age of empires ii": "https://i.ibb.co/39bd60t3/2.jpg",
    "alan wake 2": "https://i.ibb.co/3yYsJ88J/3.jpg",
    "battlefield 2042 ps5": "https://i.ibb.co/PZ7MRpM6/4.jpg",
    "death stranding": "https://i.ibb.co/DH3Fsngg/5.jpg",
    "dragon's dogma": "https://i.ibb.co/mCFdMhBJ/6.jpg",
    "ea sports fc 26 ps5": "https://i.ibb.co/6c2rzTyy/7.jpg",
    "fatal frame ii": "https://i.ibb.co/v6tcM6kV/8.jpg",
    "final fantasy vii intergrade": "https://i.ibb.co/ZDj73Wz/9.jpg",
    "ghost of tsushima director’s cut ps5": "https://i.ibb.co/TD1kmpLT/10.jpg",
    "just dance 2026": "https://i.ibb.co/V79G4Ty/11.jpg",
    "spider-man miles morales": "https://i.ibb.co/0pVyYk8m/12.jpg",
    "metal gear solid": "https://i.ibb.co/gMTCjZVV/13.jpg",
    "nioh 3": "https://i.ibb.co/QvL2bxzM/14.jpg",
    "persona 5 royal ps5": "https://i.ibb.co/x8MjV37h/15.jpg",
    "reanimal": "https://i.ibb.co/Q3mC1PWz/16.jpg",
    "silent hill 2": "https://i.ibb.co/vxGhTN9V/17.jpg",
    "silent hill f": "https://i.ibb.co/KjVDxY68/18.jpg",
    "ufc 5": "https://i.ibb.co/FkcccNQ2/19.jpg",
    "wrc 10 ps5": "https://i.ibb.co/1YNK1Fxj/20.jpg",
    "wwe 2k26 attitude": "https://i.ibb.co/vxwNrc0P/21.jpg",
    "wwe 2k26 king": "https://i.ibb.co/fzQyk7KT/22.jpg",

    // 🟦 EXCLUSIVOS DE PS4
    "battlefield 2042 ps4": "https://i.ibb.co/BVbrJ9v1/23.jpg",
    "ea sports fc 26 ps4": "https://i.ibb.co/LzZnNfd4/24.jpg",
    "final fantasy vii remake deluxe ps4": "https://i.ibb.co/S7m2Br67/25.jpg",
    "ghost of tsushima director’s cut ps4": "https://i.ibb.co/1fFQmS9q/26.jpg",
    "the last of us part ii": "https://i.ibb.co/N2V245Mf/27.jpg",
    "wrc 10 ps4": "https://i.ibb.co/d4vqz1N5/28.jpg",

    // 🟢 COMPATIBLES CON PS4 Y PS5
    "alan wake remastered": "https://i.ibb.co/NgmGC6ZH/29.jpg",
    "alien: isolation": "https://i.ibb.co/8DnhbN8d/30.jpg",
    "assassin's creed odyssey: deluxe": "https://i.ibb.co/DHgdnnMp/31.jpg",
    "assassin's creed origins": "https://i.ibb.co/yFx2Fgjp/32.jpg",
    "assassin's creed rogue": "https://i.ibb.co/4Z8H4GhP/33.jpg",
    "assassin's creed valhalla": "https://i.ibb.co/xS3Tw27B/34.jpg",
    "assassin's creed odyssey gold": "https://i.ibb.co/4nYps8sZ/35.jpg",
    "ball x pit": "https://i.ibb.co/20RYYzj3/36.jpg",
    "batman: arkham": "https://i.ibb.co/wFX5thGq/37.jpg",
    "battlefield 4": "https://i.ibb.co/yFXV8td6/38.jpg",
    "battlefield 1": "https://i.ibb.co/Z66sP1B1/39.jpg",
    "battlefield v": "https://i.ibb.co/CpskY6zq/40.jpg",
    "blasphemous": "https://i.ibb.co/LXd6Z4Y0/41.jpg",
    "bloodborne": "https://i.ibb.co/W1ckkrL/42.jpg",
    "bully": "https://i.ibb.co/bjCsztsf/43.jpg",
    "crash bandicoot crashiversary": "https://i.ibb.co/LDL7f972/44.jpg",
    "crash bandicoot quadrilogy": "https://i.ibb.co/0VqLk8Q1/45.jpg",
    "dakar 18": "https://i.ibb.co/PsVYyTbV/46.jpg",
    "dark souls ii": "https://i.ibb.co/mrZbkmJm/47.jpg",
    "dark souls iii": "https://i.ibb.co/BH4nPj3s/48.jpg",
    "dark souls iii deluxe": "https://i.ibb.co/XxLrwjJV/49.jpg",
    "dark souls remastered": "https://i.ibb.co/5hJTr11V/50.jpg",
    "dead by daylight": "https://i.ibb.co/39cj3DQn/51.jpg",
    "demon slayer hinokami": "https://i.ibb.co/YBPzLHcC/52.jpg",
    "descenders": "https://i.ibb.co/VYkQz3WW/53.jpg",
    "detroit: become human": "https://i.ibb.co/jZ5k1qm7/54.jpg",
    "deus ex mankind": "https://i.ibb.co/HTKfpRvF/55.jpg",
    "dirt 5": "https://i.ibb.co/q3x8LK9c/56.jpg",
    "dirt rally 2.0": "https://i.ibb.co/mCrznxHz/57.jpg",
    "dragon age inquisition": "https://i.ibb.co/jPMTrP1G/58.jpg",
    "dragon ball fighterz": "https://i.ibb.co/TxyZvJPv/59.jpg",
    "dragon ball z: kakarotto": "https://i.ibb.co/rRhSs29f/60.jpg",
    "dynasty warriors 9": "https://i.ibb.co/pB1b09vT/61.jpg",
    "evil west": "https://i.ibb.co/hRRs990C/62.jpg",
    "fallout 4": "https://i.ibb.co/pB5gL4k9/63.jpg",
    "far cry 5": "https://i.ibb.co/wNqx1c3S/64.jpg",
    "far cry 6 gold": "https://i.ibb.co/HDDxK26G/65.jpg",
    "far cry 3": "https://i.ibb.co/YFfXfDdV/66.jpg",
    "far cry 4": "https://i.ibb.co/Rdjr7Vh/67.jpg",
    "far cry 4 gold": "https://i.ibb.co/m5mZ2sT4/68.jpg",
    "far cry 6 deluxe": "https://i.ibb.co/G4Zv4Drq/69.jpg",
    "far cry primal": "https://i.ibb.co/zTPYxQf9/70.jpg",
    "far cry primal apex": "https://i.ibb.co/4v3rwWR/71.jpg",
    "final fantasy vii rebirth": "https://i.ibb.co/mCVXRmJk/72.jpg",
    "final fantasy vii remake + rebirth": "https://i.ibb.co/Z16Ctk7t/73.jpg",
    "five nights at freddy": "https://i.ibb.co/YFz4hLBM/74.jpg",
    "god of war": "https://i.ibb.co/TBZTjmhC/75.jpg",
    "gran turismo 7": "https://i.ibb.co/LhpxKd5z/76.jpg",
    "demon slayer deluxe": "https://i.ibb.co/jZ8N3jhn/77.jpg",
    "hazelight bundle": "https://i.ibb.co/8DTp1FbF/78.jpg",
    "hitman deluxe": "https://i.ibb.co/WWV82ks1/79.jpg",
    "hollow knight": "https://i.ibb.co/fG0Fh38S/80.jpg",
    "horizon zero dawn": "https://i.ibb.co/0yq9hrqK/81.jpg",
    "jojo all-star": "https://i.ibb.co/X95fyRV/82.jpg",
    "jojo eyes of heaven": "https://i.ibb.co/pFJNdTy/83.jpg",
    "jujutsu kaizen": "https://i.ibb.co/4RXBFnBF/84.jpg",
    "just cause 3": "https://i.ibb.co/Q75BXwvC/85.jpg",
    "just cause 4": "https://i.ibb.co/xtChh5zT/86.jpg",
    "knack 2": "https://i.ibb.co/ch83q8RL/87.jpg",
    "knack": "https://i.ibb.co/VcVqtNvh/88.jpg",
    "legacy of kain": "https://i.ibb.co/rRjb8Htn/89.jpg",
    "lego batman 3": "https://i.ibb.co/0pTkVtZk/90.jpg",
    "lego city": "https://i.ibb.co/qFFdpwY1/91.jpg",
    "lego hobbit": "https://i.ibb.co/NgpNSpXf/92.jpg",
    "lego marvel super heroes": "https://i.ibb.co/kV6MT7zv/93.jpg",
    "lego avengers": "https://i.ibb.co/6JG2rZQH/94.jpg",
    "lego star wars": "https://i.ibb.co/ccZH6Ly3/95.jpg",
    "life is strange remastered": "https://i.ibb.co/TMLgFGqQ/96.jpg",
    "life is strange true colors": "https://i.ibb.co/4nRV7xGB/97.jpg",
    "like a dragon ishin": "https://i.ibb.co/xq81DXNH/98.jpg",
    "little nightmares i": "https://i.ibb.co/zh8KST0n/99.jpg",
    "little nightmares ii": "https://i.ibb.co/pjZVSgkC/100.jpg",
    "lost judgment": "https://i.ibb.co/s9DMD1yS/101.jpg",
    "mad max": "https://i.ibb.co/zTbV0HPD/102.jpg",
    "manhunt": "https://i.ibb.co/4wJkM4WR/103.jpg",
    "middle-earth": "https://i.ibb.co/NnFf17g0/104.jpg",
    "mlb the show": "https://i.ibb.co/d013KcbZ/105.jpg",
    "monster energy supercross 4 special": "https://i.ibb.co/Z6wFVtmW/106.jpg",
    "monster energy supercross 4": "https://i.ibb.co/BVb1L1gr/107.jpg",
    "monster hunter rise + sunbreak": "https://i.ibb.co/wZ0skTyD/108.jpg",
    "monster hunter rise deluxe": "https://i.ibb.co/HDVV1PXN/109.jpg",
    "monster hunter world iceborne": "https://i.ibb.co/v4wswGt9/110.jpg",
    "mortal kombat x": "https://i.ibb.co/RGTGNwcW/111.jpg",
    "mortal kombat legacy": "https://i.ibb.co/PZNdQDyN/112.jpg",
    "moving out": "https://i.ibb.co/MyPjLmwx/113.jpg",
    "my hero one's justice 2": "https://i.ibb.co/1YwdnC10/114.jpg",
    "my hero one's justice 2 ultimate": "https://i.ibb.co/zHbszW2J/115.jpg",
    "naruto storm legacy": "https://i.ibb.co/VYV6HmLq/116.jpg",
    "need for speed deluxe": "https://i.ibb.co/RGQKHZyc/117.jpg",
    "need for speed heat": "https://i.ibb.co/r2y7r5rF/118.jpg",
    "need for speed payback": "https://i.ibb.co/G4htPNf8/119.jpg",
    "need for speed rivals": "https://i.ibb.co/hpDrPmr/120.jpg",
    "ninja gaiden": "https://i.ibb.co/XrZhnf47/121.jpg",
    "one piece world seeker": "https://i.ibb.co/xtgLNN91/122.jpg",
    "one piece pirate warriors 4": "https://i.ibb.co/JwrsyYVK/123.jpg",
    "one piece pirate warriors 4 ultimate": "https://i.ibb.co/gFffYk3f/124.jpg",
    "onimusha": "https://i.ibb.co/Psdvwjyk/176.jpg",
    "overcooked": "https://i.ibb.co/JWNLxqK0/125.jpg",
    "overcooked + overcooked 2": "https://i.ibb.co/jPdhdk0N/126.jpg",
    "persona 5 royal ultimate": "https://i.ibb.co/d0M9swzb/127.jpg",
    "phoenix wright": "https://i.ibb.co/GQ9Brkxm/128.jpg",
    "plants vs zombies": "https://i.ibb.co/cSTT1PMv/129.jpg",
    "predator hunting": "https://i.ibb.co/9HB8nqC8/130.jpg",
    "prince of persia": "https://i.ibb.co/B2wq9zDQ/131.jpg",
    "raccoon city": "https://i.ibb.co/Nnbk75MS/132.jpg",
    "resident evil 2": "https://i.ibb.co/QFgnQgg6/133.jpg",
    "resident evil 4": "https://i.ibb.co/sdP6DrDM/134.jpg",
    "resident evil 7": "https://i.ibb.co/v4W1DMPv/135.jpg",
    "resident evil revelations": "https://i.ibb.co/KpMz5xwM/136.jpg",
    "resident evil triple": "https://i.ibb.co/1tmSwtH3/137.jpg",
    "resident evil village": "https://i.ibb.co/7xZ6pcZR/138.jpg",
    "resident evil deluxe origins": "https://i.ibb.co/0yLM0chF/139.jpg",
    "skater xl": "https://i.ibb.co/MrcVSdQ/140.jpg",
    "sonic frontiers": "https://i.ibb.co/21dYM4L3/141.jpg",
    "sonic racing": "https://i.ibb.co/WW2KXgKJ/142.jpg",
    "sonic x shadow": "https://i.ibb.co/RpXBmbh0/143.jpg",
    "south park fractured": "https://i.ibb.co/yn5YzQqJ/144.jpg",
    "spyro trilogy": "https://i.ibb.co/CKrJGpXq/145.jpg",
    "stranded deep": "https://i.ibb.co/XfgQn7n3/146.jpg",
    "street fighter 30th": "https://i.ibb.co/202DH6JV/147.jpg",
    "street fighter v": "https://i.ibb.co/6RT7tn3T/148.jpg",
    "tekken 7": "https://i.ibb.co/VpN8PDjd/149.jpg",
    "tekken 7 definitive": "https://i.ibb.co/FkRD13sj/150.jpg",
    "tennis world tour": "https://i.ibb.co/1Jb9ZGC2/151.jpg",
    "tennis world tour roland": "https://i.ibb.co/nsj9Ntfz/152.jpg",
    "the crew 2": "https://i.ibb.co/qM6VGH0X/153.jpg",
    "the last guardian": "https://i.ibb.co/0L93ZKZ/154.jpg",
    "the quarry": "https://i.ibb.co/5XCrg6B7/155.jpg",
    "the warriors": "https://i.ibb.co/chTzB7cQ/156.jpg",
    "titanfall 2": "https://i.ibb.co/fLy2yHy/157.jpg",
    "ghost recon breakpoint": "https://i.ibb.co/k2NyP8pG/158.jpg",
    "ghost recon breakpoint ultimate": "https://i.ibb.co/Kxr55Kmj/159.jpg",
    "tomb raider trilogy": "https://i.ibb.co/XZ5r858h/160.jpg",
    "tony hawk": "https://i.ibb.co/kg94stj3/161.jpg",
    "uncharted collection": "https://i.ibb.co/XrWHg4Tk/162.jpg",
    "unravel bundle": "https://i.ibb.co/ynJb9prZ/163.jpg",
    "watch dogs legion deluxe": "https://i.ibb.co/nq6kmMPS/164.jpg",
    "watch dogs legion gold": "https://i.ibb.co/tTLYTpY8/165.jpg",
    "watch dogs complete": "https://i.ibb.co/spzdz7hH/166.jpg",
    "wo long fallen dynasty": "https://i.ibb.co/1thh21jv/167.jpg",
    "world war z aftermath": "https://i.ibb.co/93YkjDG5/168.jpg",
    "world war z aftermath deluxe": "https://i.ibb.co/ZR0rbW7f/169.jpg",
    "xcom 2": "https://i.ibb.co/PGhWmDJ5/170.jpg",
    "yakuza kiwami": "https://i.ibb.co/nqYV2yzd/171.jpg",
    "yakuza kiwami 2": "https://i.ibb.co/5hWkTfLQ/172.jpg",
    "yakuza kiwami 3": "https://i.ibb.co/v4yZ4N5J/173.jpg",
    "yakuza like a dragon": "https://i.ibb.co/4R0NZm80/174.jpg",
    "zombie army trilogy": "https://i.ibb.co/MyTPGR1W/175.jpg"
}